---
- name: Configure Database servers
  hosts: databases
  become: true

  tasks:
     - name: Install postgresql-server
       ansible.builtin.package:
         name: postgresql-server
         state: present

     - name: Run postgresql setup command
        

    # - name: Start and enable postgresql service
